// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARLwUIfHharQKrQeMCPqtLPTZ8fntezo',
    appId: '1:574753633765:android:1540aa8c80462b75f82b0c',
    messagingSenderId: '574753633765',
    projectId: 'studentapp-9f868',
    storageBucket: 'studentapp-9f868.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumdIkyqDMa85rqXeLvt9VUiv9BsyiNug',
    appId: '1:574753633765:web:fb0cae66341fd262f82b0c',
    messagingSenderId: '574753633765',
    projectId: 'studentapp-9f868',
    authDomain: 'studentapp-9f868.firebaseapp.com',
    storageBucket: 'studentapp-9f868.appspot.com',
    measurementId: 'G-YZ2QDYLZGT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcAGmv-Y1wD3ZizwhjiS-oyie_dDuy60E',
    appId: '1:574753633765:ios:bf9e9780ce1e9dacf82b0c',
    messagingSenderId: '574753633765',
    projectId: 'studentapp-9f868',
    storageBucket: 'studentapp-9f868.appspot.com',
    iosBundleId: 'com.example.student2',
  );

}